---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gameofblocks-__CI_ENVIRONMENT_SLUG__
  namespace: gameofblocks-__CI_ENVIRONMENT_SLUG__
  labels:
    app: gameofblocks
    ref: __CI_ENVIRONMENT_SLUG__
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  # tls:
  # - hosts:
  #   - __CI_ENVIRONMENT_SLUG__.dev.gameofblocks.io
    # the secret used here is an unsigned wildcard cert for demo purposes
    # use your own or comment this out
    # secretName: tls-wildcard-demo
  rules:
  - host: __CI_ENVIRONMENT_SLUG__.dev.gameofblocks.io
    http:
      paths:
      - path: /
        backend:
          serviceName: gameofblocks-__CI_ENVIRONMENT_SLUG__
          servicePort: 80