variables:
  # CI variables
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  GIT_STRATEGY: fetch
  GIT_DEPTH: 5
  
  # Globals
  DOCKER_VERSION: "18"
  PYTHON_VERSION: "3.6-alpine"

stages:
- "prepare"
- "build"
- "registration"
- "deploy"

include:
  - local: .gitlab/ci/base_register_stage.yml
  - local: .gitlab/ci/base_yarn_workspace_install
  - local: .gitlab/ci/1-prepare.yml
  - local: .gitlab/ci/2-build.yaml
  - local: .gitlab/ci/3-registration.yml
  - local: .gitlab/ci/4-deploy.yml