---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planetexpress-__CI_ENVIRONMENT_SLUG__
  labels:
    app: planetexpress-app
    ref: __CI_ENVIRONMENT_SLUG__
    track: stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planetexpress-app
      ref: __CI_ENVIRONMENT_SLUG__
  template:
    metadata:
      labels:
        app: planetexpress-app
        ref: __CI_ENVIRONMENT_SLUG__
        track: stable
    spec:
      imagePullSecrets:
        - name: regcred    
      containers:
      - name: app
        image: __CI_REGISTRY_IMAGE__/app:__CI_COMMIT_SHA__
        imagePullPolicy: Always
        env:
        - name: AUTH_PRIVATE_KEY
          value: "test123456"
        - name: AUTH_PUBLIC_KEY
          value: "test123456"
        - name: AUTH_KEY_ID
          value: "test123456"                    
        - name: DATABASE_URL
          value: postgres://doadmin:v301lqeez61js1fc@db-postgresql-ams3-61243-do-user-6394442-0.a.db.ondigitalocean.com:25060/defaultdb?sslmode=require
        ports:
        - name: http-metrics
          protocol: TCP
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 2