---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: planetexpress-hasura
    hasuraService: custom
  name: planetexpress-hasura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planetexpress-hasura
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: planetexpress-hasura
    spec:
      imagePullSecrets:
        - name: regcred    
      containers:
      - name: hasura
        image: __CI_REGISTRY_IMAGE__/hasura:__CI_COMMIT_SHA__
        imagePullPolicy: Always      
        env:
        - name: BASE_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: hasura-database
              key: databaseUrl
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: "$(BASE_DATABASE_URL)defaultdb"
        - name: HASURA_GRAPHQL_ACCESS_KEY
          value: secret
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        ports:
          - containerPort: 8080
            protocol: TCP