---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: planetexpress-hasura
    hasuraService: custom
  name: planetexpress-hasura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planetexpress-hasura
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: planetexpress-hasura
    spec:
      imagePullSecrets:
        - name: regcred    
      containers:
      - name: hasura
        image: __CI_REGISTRY_IMAGE__/hasura:__CI_COMMIT_SHA__
        imagePullPolicy: Always      
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: postgres://doadmin:v301lqeez61js1fc@db-postgresql-ams3-61243-do-user-6394442-0.a.db.ondigitalocean.com:25060/defaultdb
        - name: HASURA_GRAPHQL_ACCESS_KEY
          value: secret
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        ports:
          - containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 2