---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-planetexpress-__CI_ENVIRONMENT_SLUG__
  labels:
    app: planetexpress-hasura
    ref: __CI_ENVIRONMENT_SLUG__-hasura
    track: stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planetexpress-hasura
      ref: __CI_ENVIRONMENT_SLUG__-hasura
  template:
    metadata:
      labels:
        app: planetexpress-hasura
        ref: __CI_ENVIRONMENT_SLUG__-hasura
        track: stable
    spec:
      imagePullSecrets:
        - name: regcred    
      containers:
      - name: hasura
        image: __CI_REGISTRY_IMAGE__/hasura:__CI_COMMIT_SHA__
        imagePullPolicy: Always
        ports:
        - name: http-metrics
          protocol: TCP
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 2