---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hasura-planetexpress-__CI_ENVIRONMENT_SLUG__
  labels:
    app: hasura-planetexpress
    ref: hasura-__CI_ENVIRONMENT_SLUG__
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - hasura-__CI_ENVIRONMENT_SLUG__.planetexpress.dev
    secretName: hasura-__CI_ENVIRONMENT_SLUG__.planetexpress.dev
  rules:
  - host: hasura-__CI_ENVIRONMENT_SLUG__.planetexpress.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: hasura-planetexpress-__CI_ENVIRONMENT_SLUG__
          servicePort: 80