---
apiVersion: v1
kind: Service
metadata:
  name: planetexpress-hasura
  labels:
    app: planetexpress-hasura
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: planetexpress-hasura